// Assembly System.Xml.Linq, Version 4.0.0.0

[assembly: System.Runtime.CompilerServices.Extension]
[assembly: System.Security.AllowPartiallyTrustedCallers]
[assembly: System.Security.SecurityRules(System.Security.SecurityRuleSet.Level1, SkipVerificationInFullTrust=true)]
[assembly: System.Runtime.CompilerServices.CompilationRelaxations(8)]
[assembly: System.Reflection.AssemblyDefaultAlias("System.Xml.Linq.dll")]
[assembly: System.Diagnostics.Debuggable(System.Diagnostics.DebuggableAttribute.DebuggingModes.IgnoreSymbolStoreSequencePoints)]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.CLSCompliant(true)]
[assembly: System.Reflection.AssemblyCopyright("\x00a9 Microsoft Corporation.  All rights reserved.")]
[assembly: System.Reflection.AssemblyFileVersion("4.0.30319.1")]
[assembly: System.Runtime.CompilerServices.RuntimeCompatibility(WrapNonExceptionThrows=true)]
[assembly: System.Reflection.AssemblyDescription("System.Xml.Linq.dll")]
[assembly: System.Reflection.AssemblyCompany("Microsoft Corporation")]
[assembly: System.Reflection.AssemblyProduct("Microsoft\x00ae .NET Framework")]
[assembly: System.Resources.SatelliteContractVersion("4.0.0.0")]
[assembly: System.Reflection.AssemblyKeyFile(@"f:\dd\tools\devdiv\EcmaPublicKey.snk")]
[assembly: System.Reflection.AssemblyInformationalVersion("4.0.30319.1")]
[assembly: System.Reflection.AssemblyTitle("System.Xml.Linq.dll")]
[assembly: System.Resources.NeutralResourcesLanguage("en-US")]
[assembly: System.Reflection.AssemblyDelaySign(true)]
[assembly: System.Runtime.AssemblyTargetedPatchBand("1.0.21-0")]

