// Assembly System.EnterpriseServices, Version 4.0.0.0

[assembly: System.Resources.NeutralResourcesLanguage("en-US")]
[assembly: System.Reflection.AssemblyKeyFile(@"f:\dd\Tools\devdiv\finalpublickey.snk")]
[assembly: System.Resources.SatelliteContractVersion("4.0.0.0")]
[assembly: System.Reflection.AssemblyDelaySign(true)]
[assembly: System.Diagnostics.Debuggable(System.Diagnostics.DebuggableAttribute.DebuggingModes.IgnoreSymbolStoreSequencePoints)]
[assembly: System.Runtime.CompilerServices.CompilationRelaxations(8)]
[assembly: System.Runtime.CompilerServices.RuntimeCompatibility(WrapNonExceptionThrows=true)]
[assembly: System.Runtime.InteropServices.ComVisible(true)]
[assembly: System.Reflection.AssemblyInformationalVersion("4.0.30319.1")]
[assembly: System.Security.SecurityRules(System.Security.SecurityRuleSet.Level1)]
[assembly: System.Runtime.InteropServices.Guid("4fb2d46f-efc8-4643-bcd0-6e5bfa6a174c")]
[assembly: System.EnterpriseServices.ApplicationID("1e246775-2281-484f-8ad4-044c15b86eb7")]
[assembly: System.EnterpriseServices.ApplicationName(".NET Utilities")]
[assembly: System.Runtime.InteropServices.ComCompatibleVersion(1, 0, 0xce4, 0)]
[assembly: System.Runtime.InteropServices.TypeLibVersion(2, 4)]
[assembly: System.CLSCompliant(true)]
[assembly: System.Reflection.AssemblyTitle("System.EnterpriseServices.dll")]
[assembly: System.Reflection.AssemblyDescription("System.EnterpriseServices.dll")]
[assembly: System.Reflection.AssemblyDefaultAlias("System.EnterpriseServices.dll")]
[assembly: System.Reflection.AssemblyCompany("Microsoft Corporation")]
[assembly: System.Reflection.AssemblyProduct("Microsoft\x00ae .NET Framework")]
[assembly: System.Reflection.AssemblyCopyright("\x00a9 Microsoft Corporation.  All rights reserved.")]
[assembly: System.Reflection.AssemblyFileVersion("4.0.30319.1")]
[assembly: System.Security.Permissions.SecurityPermission(System.Security.Permissions.SecurityAction.RequestMinimum, SkipVerification=true)]

