// Assembly System.Runtime.Remoting, Version 4.0.0.0

[assembly: System.Runtime.CompilerServices.CompilationRelaxations(8)]
[assembly: System.Runtime.CompilerServices.RuntimeCompatibility(WrapNonExceptionThrows=true)]
[assembly: System.Runtime.InteropServices.ComCompatibleVersion(1, 0, 0xce4, 0)]
[assembly: System.Runtime.InteropServices.TypeLibVersion(4, 0)]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.CLSCompliant(false)]
[assembly: System.Reflection.AssemblyTitle("System.Runtime.Remoting.dll")]
[assembly: System.Reflection.AssemblyDescription("System.Runtime.Remoting.dll")]
[assembly: System.Reflection.AssemblyDefaultAlias("System.Runtime.Remoting.dll")]
[assembly: System.Reflection.AssemblyCompany("Microsoft Corporation")]
[assembly: System.Reflection.AssemblyProduct("Microsoft\x00ae .NET Framework")]
[assembly: System.Reflection.AssemblyCopyright("\x00a9 Microsoft Corporation.  All rights reserved.")]
[assembly: System.Reflection.AssemblyFileVersion("4.0.30319.1")]
[assembly: System.Reflection.AssemblyInformationalVersion("4.0.30319.1")]
[assembly: System.Resources.SatelliteContractVersion("4.0.0.0")]
[assembly: System.Resources.NeutralResourcesLanguage("en-US")]
[assembly: System.Reflection.AssemblyDelaySign(true)]
[assembly: System.Reflection.AssemblyKeyFile(@"f:\dd\Tools\devdiv\ecmapublickey.snk")]
[assembly: System.Diagnostics.Debuggable(System.Diagnostics.DebuggableAttribute.DebuggingModes.IgnoreSymbolStoreSequencePoints)]
[assembly: System.Runtime.AssemblyTargetedPatchBand("1.0.21-0")]
[assembly: System.Security.Permissions.SecurityPermission(System.Security.Permissions.SecurityAction.RequestMinimum, SkipVerification=true)]

