// Assembly System.Data.OracleClient, Version 4.0.0.0

[assembly: System.Resources.SatelliteContractVersion("4.0.0.0")]
[assembly: System.Reflection.AssemblyProduct("Microsoft\x00ae .NET Framework")]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.Runtime.CompilerServices.RuntimeCompatibility(WrapNonExceptionThrows=true)]
[assembly: System.Reflection.AssemblyInformationalVersion("4.0.30319.1")]
[assembly: System.Reflection.AssemblyFileVersion("4.0.30319.1")]
[assembly: System.Reflection.AssemblyCopyright("\x00a9 Microsoft Corporation.  All rights reserved.")]
[assembly: System.Reflection.AssemblyDescription("System.Data.OracleClient.dll")]
[assembly: System.Runtime.CompilerServices.Dependency("System.Data,", System.Runtime.CompilerServices.LoadHint.Always)]
[assembly: System.Reflection.AssemblyDelaySign(true)]
[assembly: System.CLSCompliant(true)]
[assembly: System.Reflection.AssemblyKeyFile(@"f:\dd\Tools\devdiv\ecmapublickey.snk")]
[assembly: System.Reflection.AssemblyDefaultAlias("System.Data.OracleClient.dll")]
[assembly: System.Resources.NeutralResourcesLanguage("en-US")]
[assembly: System.Runtime.InteropServices.ComCompatibleVersion(1, 0, 0xce4, 0)]
[assembly: System.Reflection.AssemblyCompany("Microsoft Corporation")]
[assembly: System.Reflection.AssemblyTitle("System.Data.OracleClient.dll")]
[assembly: System.Security.SecurityRules(System.Security.SecurityRuleSet.Level1, SkipVerificationInFullTrust=true)]
[assembly: System.Security.AllowPartiallyTrustedCallers]
[assembly: System.Security.Permissions.SecurityPermission(System.Security.Permissions.SecurityAction.RequestMinimum, SkipVerification=true)]

