// Assembly Microsoft.VisualBasic, Version 10.0.0.0

[assembly: System.Reflection.AssemblyDescription("Microsoft.VisualBasic.dll")]
[assembly: System.Reflection.AssemblyTitle("Microsoft.VisualBasic.dll")]
[assembly: System.Security.SecurityRules(System.Security.SecurityRuleSet.Level2)]
[assembly: System.Reflection.AssemblyDefaultAlias("Microsoft.VisualBasic.dll")]
[assembly: System.Runtime.CompilerServices.RuntimeCompatibility(WrapNonExceptionThrows=true)]
[assembly: System.Reflection.AssemblyCompany("Microsoft Corporation")]
[assembly: System.Security.AllowPartiallyTrustedCallers]
[assembly: System.CLSCompliant(true)]
[assembly: System.Runtime.InteropServices.ComVisible(true)]
[assembly: System.Reflection.AssemblyDelaySign(true)]
[assembly: System.Diagnostics.Debuggable(System.Diagnostics.DebuggableAttribute.DebuggingModes.IgnoreSymbolStoreSequencePoints | System.Diagnostics.DebuggableAttribute.DebuggingModes.Default)]
[assembly: System.Runtime.CompilerServices.CompilationRelaxations(8)]
[assembly: System.Runtime.Versioning.TargetFramework(".NETFramework,Version=v4.0", FrameworkDisplayName="")]
[assembly: System.Reflection.AssemblyKeyFile(@"f:\\dd\\tools\\devdiv\\FinalPublicKey.snk")]
[assembly: System.Reflection.AssemblyInformationalVersion("10.0.30319.1")]
[assembly: System.Reflection.AssemblyProduct("Microsoft (R) Visual Studio (R) 2010")]
[assembly: System.Resources.SatelliteContractVersion("10.0.0.0")]
[assembly: System.Resources.NeutralResourcesLanguage("en-US")]
[assembly: System.Reflection.AssemblyFileVersion("10.0.30319.1")]
[assembly: System.Reflection.AssemblyCopyright("\x00a9 Microsoft Corporation. All rights reserved.")]
[assembly: System.Runtime.AssemblyTargetedPatchBand("1.0.21-0")]

