namespace System.Web.Security
{
    using System;
    using System.Web;

    internal class DefaultMembershipAdapter : IMembershipAdapter
    {
        public byte[] EncryptOrDecryptData(bool encrypt, byte[] buffer, bool useLegacyMode)
        {
            throw new PlatformNotSupportedException(ApplicationServicesStrings.Platform_not_supported);
        }

        public bool IsDecryptionKeyAutogenerated
        {
            get
            {
                throw new PlatformNotSupportedException(ApplicationServicesStrings.Platform_not_supported);
            }
        }

        public MembershipProviderCollection Providers
        {
            get
            {
                throw new PlatformNotSupportedException(ApplicationServicesStrings.Platform_not_supported);
            }
        }

        public int UserIsOnlineTimeWindow
        {
            get
            {
                throw new PlatformNotSupportedException(ApplicationServicesStrings.Platform_not_supported);
            }
        }

        public bool UsingCustomEncryption
        {
            get
            {
                throw new PlatformNotSupportedException(ApplicationServicesStrings.Platform_not_supported);
            }
        }
    }
}

