namespace System.Web.Security
{
    using System;

    internal interface IMembershipAdapter
    {
        byte[] EncryptOrDecryptData(bool encrypt, byte[] buffer, bool useLegacyMode);

        bool IsDecryptionKeyAutogenerated { get; }

        MembershipProviderCollection Providers { get; }

        int UserIsOnlineTimeWindow { get; }

        bool UsingCustomEncryption { get; }
    }
}

