// Assembly System.Xaml, Version 4.0.0.0

[assembly: System.Reflection.AssemblyKeyFile(@"f:\dd\tools\devdiv\EcmaPublicKey.snk")]
[assembly: System.Runtime.CompilerServices.Dependency("mscorlib,", System.Runtime.CompilerServices.LoadHint.Always)]
[assembly: System.Reflection.AssemblyDefaultAlias("System.Xaml.dll")]
[assembly: System.Reflection.AssemblyCompany("Microsoft Corporation")]
[assembly: System.Reflection.AssemblyProduct("Microsoft\x00ae .NET Framework")]
[assembly: System.Reflection.AssemblyDescription("System.Xaml.dll")]
[assembly: System.Runtime.CompilerServices.RuntimeCompatibility(WrapNonExceptionThrows=true)]
[assembly: System.Runtime.CompilerServices.Dependency("System,", System.Runtime.CompilerServices.LoadHint.Always)]
[assembly: System.Security.SecurityRules(System.Security.SecurityRuleSet.Level2, SkipVerificationInFullTrust=true)]
[assembly: System.Reflection.AssemblyCopyright("\x00a9 Microsoft Corporation.  All rights reserved.")]
[assembly: System.Reflection.AssemblyFileVersion("4.0.30319.298")]
[assembly: System.Reflection.AssemblyInformationalVersion("4.0.30319.298")]
[assembly: System.Resources.SatelliteContractVersion("4.0.0.0")]
[assembly: System.Resources.NeutralResourcesLanguage("en-US")]
[assembly: System.Reflection.AssemblyDelaySign(true)]
[assembly: System.Reflection.AssemblyTitle("System.Xaml.dll")]
[assembly: System.Runtime.CompilerServices.Dependency("System.Xml,", System.Runtime.CompilerServices.LoadHint.Sometimes)]
[assembly: System.Windows.Markup.XmlnsDefinition("http://schemas.microsoft.com/winfx/2006/xaml", "System.Windows.Markup")]
[assembly: System.Diagnostics.Debuggable(System.Diagnostics.DebuggableAttribute.DebuggingModes.IgnoreSymbolStoreSequencePoints)]
[assembly: System.Runtime.CompilerServices.CompilationRelaxations(8)]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.CLSCompliant(true)]
[assembly: System.Security.AllowPartiallyTrustedCallers]
[assembly: System.Security.Permissions.SecurityPermission(System.Security.Permissions.SecurityAction.RequestMinimum, Execution=true)]
[assembly: System.Security.Permissions.SecurityPermission(System.Security.Permissions.SecurityAction.RequestMinimum, SkipVerification=true)]

