namespace System.Deployment.Internal.Isolation.Manifest
{
    using System;

    internal enum CMS_ASSEMBLY_REFERENCE_FLAG
    {
        CMS_ASSEMBLY_REFERENCE_FLAG_CULTURE_WILDCARDED = 0x10,
        CMS_ASSEMBLY_REFERENCE_FLAG_FOLLOW = 4,
        CMS_ASSEMBLY_REFERENCE_FLAG_IS_PLATFORM = 8,
        CMS_ASSEMBLY_REFERENCE_FLAG_OPTIONAL = 1,
        CMS_ASSEMBLY_REFERENCE_FLAG_PREREQUISITE = 0x80,
        CMS_ASSEMBLY_REFERENCE_FLAG_PROCESSOR_ARCHITECTURE_WILDCARDED = 0x20,
        CMS_ASSEMBLY_REFERENCE_FLAG_VISIBLE = 2
    }
}

