namespace System.Deployment.Internal.Isolation.Manifest
{
    using System;

    internal enum CMS_REGISTRY_VALUE_TYPE
    {
        CMS_REGISTRY_VALUE_TYPE_NONE,
        CMS_REGISTRY_VALUE_TYPE_SZ,
        CMS_REGISTRY_VALUE_TYPE_EXPAND_SZ,
        CMS_REGISTRY_VALUE_TYPE_MULTI_SZ,
        CMS_REGISTRY_VALUE_TYPE_BINARY,
        CMS_REGISTRY_VALUE_TYPE_DWORD,
        CMS_REGISTRY_VALUE_TYPE_DWORD_LITTLE_ENDIAN,
        CMS_REGISTRY_VALUE_TYPE_DWORD_BIG_ENDIAN,
        CMS_REGISTRY_VALUE_TYPE_LINK,
        CMS_REGISTRY_VALUE_TYPE_RESOURCE_LIST,
        CMS_REGISTRY_VALUE_TYPE_FULL_RESOURCE_DESCRIPTOR,
        CMS_REGISTRY_VALUE_TYPE_RESOURCE_REQUIREMENTS_LIST,
        CMS_REGISTRY_VALUE_TYPE_QWORD,
        CMS_REGISTRY_VALUE_TYPE_QWORD_LITTLE_ENDIAN
    }
}

