namespace System.Deployment.Internal.Isolation.Manifest
{
    using System;

    internal enum CMS_SYSTEM_PROTECTION
    {
        CMS_SYSTEM_PROTECTION_APPLICATION_AND_USER_VIRTUALIZED = 8,
        CMS_SYSTEM_PROTECTION_APPLICATION_VIRTUALIZED = 6,
        CMS_SYSTEM_PROTECTION_INHERIT = 9,
        CMS_SYSTEM_PROTECTION_NOT_PROTECTED = 10,
        CMS_SYSTEM_PROTECTION_OS_ONLY_FAIL_WRITES = 4,
        CMS_SYSTEM_PROTECTION_OS_ONLY_IGNORE_WRITES = 3,
        CMS_SYSTEM_PROTECTION_READ_ONLY_FAIL_WRITES = 2,
        CMS_SYSTEM_PROTECTION_READ_ONLY_IGNORE_WRITES = 1,
        CMS_SYSTEM_PROTECTION_TRANSACTED = 5,
        CMS_SYSTEM_PROTECTION_USER_VIRTUALIZED = 7
    }
}

