namespace System.Deployment.Internal.Isolation.Manifest
{
    using System;

    internal enum CMS_ASSEMBLY_DEPLOYMENT_FLAG
    {
        CMS_ASSEMBLY_DEPLOYMENT_FLAG_BEFORE_APPLICATION_STARTUP = 4,
        CMS_ASSEMBLY_DEPLOYMENT_FLAG_CREATE_DESKTOP_SHORTCUT = 0x200,
        CMS_ASSEMBLY_DEPLOYMENT_FLAG_DISALLOW_URL_ACTIVATION = 0x80,
        CMS_ASSEMBLY_DEPLOYMENT_FLAG_INSTALL = 0x20,
        CMS_ASSEMBLY_DEPLOYMENT_FLAG_MAP_FILE_EXTENSIONS = 0x100,
        CMS_ASSEMBLY_DEPLOYMENT_FLAG_RUN_AFTER_INSTALL = 0x10,
        CMS_ASSEMBLY_DEPLOYMENT_FLAG_TRUST_URL_PARAMETERS = 0x40
    }
}

