// Assembly System.ServiceModel.Activities, Version 4.0.0.0

[assembly: System.Reflection.AssemblyDelaySign(true)]
[assembly: System.Runtime.CompilerServices.CompilationRelaxations(8)]
[assembly: System.Resources.NeutralResourcesLanguage("en-US")]
[assembly: System.Reflection.AssemblyKeyFile(@"f:\dd\tools\devdiv\35MSSharedLib1024.snk")]
[assembly: System.Runtime.CompilerServices.RuntimeCompatibility(WrapNonExceptionThrows=true)]
[assembly: System.Windows.Markup.XmlnsDefinition("http://schemas.microsoft.com/netfx/2009/xaml/servicemodel", "System.ServiceModel")]
[assembly: System.Windows.Markup.XmlnsDefinition("http://schemas.microsoft.com/netfx/2009/xaml/servicemodel", "System.ServiceModel.Activities")]
[assembly: System.Diagnostics.Debuggable(System.Diagnostics.DebuggableAttribute.DebuggingModes.IgnoreSymbolStoreSequencePoints)]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.CLSCompliant(true)]
[assembly: System.Reflection.AssemblyTitle("System.ServiceModel.Activities.dll")]
[assembly: System.Reflection.AssemblyDescription("System.ServiceModel.Activities.dll")]
[assembly: System.Reflection.AssemblyDefaultAlias("System.ServiceModel.Activities.dll")]
[assembly: System.Reflection.AssemblyCompany("Microsoft Corporation")]
[assembly: System.Reflection.AssemblyProduct("Microsoft\x00ae .NET Framework")]
[assembly: System.Reflection.AssemblyCopyright("\x00a9 Microsoft Corporation.  All rights reserved.")]
[assembly: System.Reflection.AssemblyFileVersion("4.0.30319.245")]
[assembly: System.Reflection.AssemblyInformationalVersion("4.0.30319.245")]
[assembly: System.Resources.SatelliteContractVersion("4.0.0.0")]
[assembly: System.Security.Permissions.SecurityPermission(System.Security.Permissions.SecurityAction.RequestMinimum, Execution=true)]

