// Assembly Microsoft.Workflow.Compiler, Version 4.0.0.0

[assembly: System.Reflection.AssemblyDescription("Microsoft.Workflow.Compiler.exe")]
[assembly: System.Reflection.AssemblyDefaultAlias("Microsoft.Workflow.Compiler.exe")]
[assembly: System.Reflection.AssemblyCompany("Microsoft Corporation")]
[assembly: System.Runtime.CompilerServices.RuntimeCompatibility(WrapNonExceptionThrows=true)]
[assembly: System.Reflection.AssemblyFileVersion("4.0.30319.1")]
[assembly: System.Runtime.CompilerServices.CompilationRelaxations(8)]
[assembly: System.CLSCompliant(true)]
[assembly: System.Reflection.AssemblyTitle("Microsoft.Workflow.Compiler.exe")]
[assembly: System.Reflection.AssemblyInformationalVersion("4.0.30319.1")]
[assembly: System.Reflection.AssemblyProduct("Microsoft\x00ae .NET Framework")]
[assembly: System.Reflection.AssemblyCopyright("\x00a9 Microsoft Corporation.  All rights reserved.")]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.Resources.NeutralResourcesLanguage("en-US")]
[assembly: System.Resources.SatelliteContractVersion("4.0.0.0")]
[assembly: System.Reflection.AssemblyDelaySign(true)]
[assembly: System.Reflection.AssemblyKeyFile(@"f:\dd\Tools\devdiv\35MSSharedLib1024.snk")]
[assembly: System.Diagnostics.Debuggable(System.Diagnostics.DebuggableAttribute.DebuggingModes.IgnoreSymbolStoreSequencePoints)]
[assembly: System.Security.Permissions.SecurityPermission(System.Security.Permissions.SecurityAction.RequestMinimum, SkipVerification=true)]

