namespace System.Windows.Forms.Design
{
    using System;
    using System.Collections;
    using System.ComponentModel;
    using System.Windows.Forms;

    internal class ToolStripDropDownItemDesigner : ToolStripItemDesigner
    {
        public override void Initialize(IComponent component)
        {
            base.Initialize(component);
        }

        public override ICollection AssociatedComponents
        {
            get
            {
                ToolStripDropDownItem component = base.Component as ToolStripDropDownItem;
                if ((component != null) && component.DropDown.IsAutoGenerated)
                {
                    return component.DropDownItems;
                }
                return base.AssociatedComponents;
            }
        }
    }
}

