namespace System.Deployment.Internal.Isolation.Manifest
{
    using System;

    internal enum CMSSECTIONID
    {
        CMSSECTIONENTRYID_METADATA = 12,
        CMSSECTIONID_ASSEMBLY_REFERENCE_SECTION = 6,
        CMSSECTIONID_ASSEMBLY_REQUEST_SECTION = 13,
        CMSSECTIONID_CATEGORY_INSTANCE_SECTION = 2,
        CMSSECTIONID_CLR_SURROGATE_SECTION = 5,
        CMSSECTIONID_COM_REDIRECTION_SECTION = 3,
        CMSSECTIONID_COMPATIBLE_FRAMEWORKS_SECTION = 0x13,
        CMSSECTIONID_COUNTER_SECTION = 0x6f,
        CMSSECTIONID_COUNTERSET_SECTION = 110,
        CMSSECTIONID_DIRECTORY_SECTION = 0x11,
        CMSSECTIONID_ENTRYPOINT_SECTION = 10,
        CMSSECTIONID_EVENT_MAP_SECTION = 0x66,
        CMSSECTIONID_EVENT_SECTION = 0x65,
        CMSSECTIONID_EVENT_TAG_SECTION = 0x67,
        CMSSECTIONID_FILE_ASSOCIATION_SECTION = 0x12,
        CMSSECTIONID_FILE_SECTION = 1,
        CMSSECTIONID_PERMISSION_SET_SECTION = 11,
        CMSSECTIONID_PROGID_REDIRECTION_SECTION = 4,
        CMSSECTIONID_REGISTRY_KEY_SECTION = 0x10,
        CMSSECTIONID_STRING_SECTION = 9,
        CMSSECTIONID_WINDOW_CLASS_SECTION = 8
    }
}

