// Assembly System.Web, Version 4.0.0.0

[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("System.Web.Routing.Test, PublicKey=002400000480000094000000060200000024000052534131000400000100010007d1fa57c4aed9f0a32e84aa0faefd0de9e8fd6aec8f87fb03766c834c99921eb23be79ad9d5dcc1dd9ad236132102900b723cf980957fc4e177108fc607774f29e8320e92ea05ece4e821c0a5efe8f1645c4c0c93c1ab99285d622caa652c1dfad63d745d6f2de5f17e5eaf0fc4963d261c8a12436518206dc093344d5ad293")]
[assembly: System.Runtime.CompilerServices.RuntimeCompatibility(WrapNonExceptionThrows=true)]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("System.Web.Test, PublicKey=002400000480000094000000060200000024000052534131000400000100010007d1fa57c4aed9f0a32e84aa0faefd0de9e8fd6aec8f87fb03766c834c99921eb23be79ad9d5dcc1dd9ad236132102900b723cf980957fc4e177108fc607774f29e8320e92ea05ece4e821c0a5efe8f1645c4c0c93c1ab99285d622caa652c1dfad63d745d6f2de5f17e5eaf0fc4963d261c8a12436518206dc093344d5ad293")]
[assembly: System.Web.UI.WebResource("add_permissions_for_users.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("properties_security_tab_w_user.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("properties_security_tab.gif", "image/gif")]
[assembly: System.Runtime.InteropServices.TypeLibVersion(2, 4)]
[assembly: System.Diagnostics.Debuggable(System.Diagnostics.DebuggableAttribute.DebuggingModes.IgnoreSymbolStoreSequencePoints)]
[assembly: System.Runtime.CompilerServices.CompilationRelaxations(8)]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.CLSCompliant(true)]
[assembly: System.Security.AllowPartiallyTrustedCallers(PartialTrustVisibilityLevel=System.Security.PartialTrustVisibilityLevel.NotVisibleByDefault)]
[assembly: System.Security.SecurityRules(System.Security.SecurityRuleSet.Level1, SkipVerificationInFullTrust=true)]
[assembly: System.Reflection.AssemblyTitle("System.Web.dll")]
[assembly: System.Reflection.AssemblyDescription("System.Web.dll")]
[assembly: System.Reflection.AssemblyDefaultAlias("System.Web.dll")]
[assembly: System.Reflection.AssemblyCompany("Microsoft Corporation")]
[assembly: System.Reflection.AssemblyProduct("Microsoft\x00ae .NET Framework")]
[assembly: System.Reflection.AssemblyCopyright("\x00a9 Microsoft Corporation.  All rights reserved.")]
[assembly: System.Reflection.AssemblyFileVersion("4.0.30319.272")]
[assembly: System.Reflection.AssemblyInformationalVersion("4.0.30319.272")]
[assembly: System.Resources.SatelliteContractVersion("4.0.0.0")]
[assembly: System.Resources.NeutralResourcesLanguage("en-US")]
[assembly: System.Reflection.AssemblyDelaySign(true)]
[assembly: System.Reflection.AssemblyKeyFile(@"f:\dd\tools\devdiv\FinalPublicKey.snk")]
[assembly: System.Runtime.CompilerServices.Dependency("System,", System.Runtime.CompilerServices.LoadHint.Always)]
[assembly: System.Web.UI.TagPrefix("System.Web.UI.WebControls", "asp")]
[assembly: System.Web.UI.WebResource("WebForms.js", "application/x-javascript", CdnSupportsSecureConnection=true, CdnPath="http://ajax.microsoft.com/ajax/4.0/2/WebForms.js")]
[assembly: System.Web.UI.WebResource("Focus.js", "application/x-javascript", CdnSupportsSecureConnection=true, CdnPath="http://ajax.microsoft.com/ajax/4.0/2/Focus.js")]
[assembly: System.Web.UI.WebResource("SmartNav.htm", "text/html")]
[assembly: System.Web.UI.WebResource("SmartNav.js", "application/x-javascript")]
[assembly: System.Web.UI.WebResource("WebUIValidation.js", "application/x-javascript", CdnSupportsSecureConnection=true, CdnPath="http://ajax.microsoft.com/ajax/4.0/2/WebUIValidation.js")]
[assembly: System.Web.UI.WebResource("TreeView.js", "application/x-javascript", CdnSupportsSecureConnection=true, CdnPath="http://ajax.microsoft.com/ajax/4.0/2/TreeView.js")]
[assembly: System.Web.UI.WebResource("Menu.js", "application/x-javascript", CdnSupportsSecureConnection=true, CdnPath="http://ajax.microsoft.com/ajax/4.0/2/Menu.js")]
[assembly: System.Web.UI.WebResource("MenuStandards.js", "application/x-javascript", CdnSupportsSecureConnection=true, CdnPath="http://ajax.microsoft.com/ajax/4.0/2/MenuStandards.js")]
[assembly: System.Web.UI.WebResource("WebParts.js", "application/x-javascript", CdnSupportsSecureConnection=true, CdnPath="http://ajax.microsoft.com/ajax/4.0/2/WebParts.js")]
[assembly: System.Web.UI.WebResource("GridView.js", "application/x-javascript", CdnSupportsSecureConnection=true, CdnPath="http://ajax.microsoft.com/ajax/4.0/2/GridView.js")]
[assembly: System.Web.UI.WebResource("DetailsView.js", "application/x-javascript", CdnSupportsSecureConnection=true, CdnPath="http://ajax.microsoft.com/ajax/4.0/2/DetailsView.js")]
[assembly: System.Web.UI.WebResource("Spacer.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("Menu_Default_Separator.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("Menu_Popout.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("Menu_ScrollDown.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("Menu_ScrollUp.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("TreeView_Default_Dash.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("TreeView_Default_DashCollapse.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("TreeView_Default_DashExpand.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("TreeView_Default_I.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("TreeView_Default_L.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("TreeView_Default_LCollapse.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("TreeView_Default_LExpand.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("TreeView_Default_R.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("TreeView_Default_RCollapse.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("TreeView_Default_RExpand.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("TreeView_Default_T.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("TreeView_Default_TCollapse.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("TreeView_Default_TExpand.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("TreeView_Default_Expand.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("TreeView_Default_Collapse.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("TreeView_Default_NoExpand.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("TreeView_XP_Explorer_Expand.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("TreeView_XP_Explorer_Collapse.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("TreeView_XP_Explorer_NoExpand.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("TreeView_XP_Explorer_RootNode.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("TreeView_XP_Explorer_ParentNode.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("TreeView_XP_Explorer_LeafNode.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("TreeView_MSDN_Expand.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("TreeView_MSDN_Collapse.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("TreeView_MSDN_NoExpand.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("TreeView_Windows_Help_Expand.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("TreeView_Windows_Help_Collapse.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("TreeView_Windows_Help_NoExpand.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("TreeView_Arrows_Collapse.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("TreeView_Arrows_Expand.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("TreeView_Arrows_NoExpand.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("TreeView_BulletedList2_LeafNode.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("TreeView_BulletedList2_ParentNode.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("TreeView_BulletedList2_RootNode.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("TreeView_BulletedList3_LeafNode.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("TreeView_BulletedList3_ParentNode.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("TreeView_BulletedList3_RootNode.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("TreeView_BulletedList4_LeafNode.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("TreeView_BulletedList4_ParentNode.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("TreeView_BulletedList4_RootNode.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("TreeView_BulletedList_LeafNode.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("TreeView_BulletedList_ParentNode.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("TreeView_BulletedList_RootNode.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("TreeView_Contacts_Collapse.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("TreeView_Contacts_Expand.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("TreeView_Contacts_NoExpand.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("TreeView_Events_LeafNode.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("TreeView_Events_ParentNode.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("TreeView_Events_RootNode.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("TreeView_FAQ_LeafNode.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("TreeView_FAQ_ParentNode.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("TreeView_FAQ_RootNode.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("TreeView_Inbox_LeafNode.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("TreeView_Inbox_ParentNode.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("TreeView_Inbox_RootNode.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("TreeView_News_LeafNode.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("TreeView_News_ParentNode.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("TreeView_News_RootNode.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("TreeView_Simple2_NoExpand.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("TreeView_Simple_NoExpand.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("WebPartMenu_Check.gif", "image/gif")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("System.Design, PublicKey=002400000480000094000000060200000024000052534131000400000100010007d1fa57c4aed9f0a32e84aa0faefd0de9e8fd6aec8f87fb03766c834c99921eb23be79ad9d5dcc1dd9ad236132102900b723cf980957fc4e177108fc607774f29e8320e92ea05ece4e821c0a5efe8f1645c4c0c93c1ab99285d622caa652c1dfad63d745d6f2de5f17e5eaf0fc4963d261c8a12436518206dc093344d5ad293")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("System.Web.Extensions, PublicKey=0024000004800000940000000602000000240000525341310004000001000100b5fc90e7027f67871e773a8fde8938c81dd402ba65b9201d60593e96c492651e889cc13f1415ebb53fac1131ae0bd333c5ee6021672d9718ea31a8aebd0da0072f25d87dba6fc90ffd598ed4da35e44c398c454307e8e33b8426143daec9f596836f97c8f74750e5975c64e2189f45def46b2a2b1247adc3652bf5c308055da9")]
[assembly: System.Security.Permissions.SecurityPermission(System.Security.Permissions.SecurityAction.RequestMinimum, SkipVerification=true)]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Web.Security.RoleProvider))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Web.Security.MembershipPasswordException))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Web.Security.MembershipValidatePasswordEventHandler))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Web.Security.ValidatePasswordEventArgs))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Web.Security.MembershipCreateStatus))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Web.Security.MembershipCreateUserException))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Web.Security.MembershipPasswordFormat))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Web.Security.MembershipProvider))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Web.Security.MembershipProviderCollection))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Web.Security.MembershipUser))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Web.Security.MembershipUserCollection))]

