namespace System.Windows.Forms
{
    using System;

    public enum AccessibleRole
    {
        Alert = 8,
        Animation = 0x36,
        Application = 14,
        Border = 0x13,
        ButtonDropDown = 0x38,
        ButtonDropDownGrid = 0x3a,
        ButtonMenu = 0x39,
        Caret = 7,
        Cell = 0x1d,
        Character = 0x20,
        Chart = 0x11,
        CheckButton = 0x2c,
        Client = 10,
        Clock = 0x3d,
        Column = 0x1b,
        ColumnHeader = 0x19,
        ComboBox = 0x2e,
        Cursor = 6,
        Default = -1,
        Diagram = 0x35,
        Dial = 0x31,
        Dialog = 0x12,
        Document = 15,
        DropList = 0x2f,
        Equation = 0x37,
        Graphic = 40,
        Grip = 4,
        Grouping = 20,
        HelpBalloon = 0x1f,
        HotkeyField = 50,
        Indicator = 0x27,
        IpAddress = 0x3f,
        Link = 30,
        List = 0x21,
        ListItem = 0x22,
        MenuBar = 2,
        MenuItem = 12,
        MenuPopup = 11,
        None = 0,
        Outline = 0x23,
        OutlineButton = 0x40,
        OutlineItem = 0x24,
        PageTab = 0x25,
        PageTabList = 60,
        Pane = 0x10,
        ProgressBar = 0x30,
        PropertyPage = 0x26,
        PushButton = 0x2b,
        RadioButton = 0x2d,
        Row = 0x1c,
        RowHeader = 0x1a,
        ScrollBar = 3,
        Separator = 0x15,
        Slider = 0x33,
        Sound = 5,
        SpinButton = 0x34,
        SplitButton = 0x3e,
        StaticText = 0x29,
        StatusBar = 0x17,
        Table = 0x18,
        Text = 0x2a,
        TitleBar = 1,
        ToolBar = 0x16,
        ToolTip = 13,
        WhiteSpace = 0x3b,
        Window = 9
    }
}

