// Assembly System.Core, Version 4.0.0.0

[assembly: System.Reflection.AssemblyKeyFile(@"f:\dd\tools\devdiv\EcmaPublicKey.snk")]
[assembly: System.Security.SecurityCritical]
[assembly: System.Resources.NeutralResourcesLanguage("en-US")]
[assembly: System.Runtime.CompilerServices.StringFreezing]
[assembly: System.Resources.SatelliteContractVersion("4.0.0.0")]
[assembly: System.Security.AllowPartiallyTrustedCallers]
[assembly: System.Reflection.AssemblyInformationalVersion("4.0.30319.233")]
[assembly: System.Runtime.CompilerServices.RuntimeCompatibility(WrapNonExceptionThrows=true)]
[assembly: System.Runtime.CompilerServices.DefaultDependency(System.Runtime.CompilerServices.LoadHint.Always)]
[assembly: System.Diagnostics.Debuggable(System.Diagnostics.DebuggableAttribute.DebuggingModes.IgnoreSymbolStoreSequencePoints)]
[assembly: System.Runtime.CompilerServices.Extension]
[assembly: System.Runtime.CompilerServices.CompilationRelaxations(8)]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.CLSCompliant(true)]
[assembly: System.Reflection.AssemblyDelaySign(true)]
[assembly: System.Security.SecurityRules(System.Security.SecurityRuleSet.Level1, SkipVerificationInFullTrust=true)]
[assembly: System.Reflection.AssemblyTitle("System.Core.dll")]
[assembly: System.Reflection.AssemblyDescription("System.Core.dll")]
[assembly: System.Reflection.AssemblyDefaultAlias("System.Core.dll")]
[assembly: System.Reflection.AssemblyCompany("Microsoft Corporation")]
[assembly: System.Reflection.AssemblyProduct("Microsoft\x00ae .NET Framework")]
[assembly: System.Reflection.AssemblyCopyright("\x00a9 Microsoft Corporation.  All rights reserved.")]
[assembly: System.Reflection.AssemblyFileVersion("4.0.30319.233")]
[assembly: System.Security.Permissions.SecurityPermission(System.Security.Permissions.SecurityAction.RequestMinimum, SkipVerification=true)]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Threading.LockRecursionException))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.InvalidTimeZoneException))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.TimeZoneNotFoundException))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.TimeZoneInfo))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Security.Cryptography.Aes))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Lazy<T><>))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Threading.LazyThreadSafetyMode))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Action))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Action<T1,T2><,>))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Action<T1,T2,T3><,,>))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Action<T1,T2,T3,T4><,,,>))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Func<TResult><>))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Func<T,TResult><,>))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Func<T1,T2,TResult><,,>))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Func<T1,T2,T3,TResult><,,,>))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Func<T1,T2,T3,T4,TResult><,,,,>))]

