namespace System.Reflection
{
    using System;

    [Serializable]
    internal enum MetadataColumnType
    {
        Assembly = 0x20,
        AssemblyOS = 0x22,
        AssemblyProcessor = 0x21,
        AssemblyRef = 0x23,
        AssemblyRefOS = 0x25,
        AssemblyRefProcessor = 0x24,
        BlobHeap = 0x67,
        Byte = 100,
        ClassLayout = 15,
        CodedToken = 0x40,
        CodedTokenMax = 0x5f,
        Constant = 11,
        CustomAttribute = 12,
        CustomAttributeType = 0x4b,
        DeclSecurity = 14,
        ENCLog = 30,
        ENCMap = 0x1f,
        Event = 20,
        EventMap = 0x12,
        EventPtr = 0x13,
        ExportedType = 0x27,
        Field = 4,
        FieldLayout = 0x10,
        FieldMarshal = 13,
        FieldPtr = 3,
        FieldRVA = 0x1d,
        File = 0x26,
        GenericParam = 0x2a,
        GenericParamConstraint = 0x2c,
        GuidHeap = 0x66,
        HasConstant = 0x42,
        HasCustomAttribute = 0x43,
        HasDeclSecurity = 0x45,
        HasFieldMarshal = 0x44,
        HasSemantic = 0x47,
        Implementation = 0x4a,
        ImplMap = 0x1c,
        InterfaceImpl = 9,
        Long = 0x62,
        ManifestResource = 40,
        MemberForwarded = 0x49,
        MemberRef = 10,
        MemberRefParent = 70,
        Method = 6,
        MethodDefOrRef = 0x48,
        MethodImpl = 0x19,
        MethodPtr = 5,
        MethodSemantics = 0x18,
        MethodSpec = 0x2b,
        Module = 0,
        ModuleRef = 0x1a,
        NestedClass = 0x29,
        Param = 8,
        ParamPtr = 7,
        Property = 0x17,
        PropertyMap = 0x15,
        PropertyPtr = 0x16,
        ResolutionScope = 0x4c,
        Short = 0x60,
        StandAloneSig = 0x11,
        StringHeap = 0x65,
        TableIdMax = 0x3f,
        TypeDef = 2,
        TypeDefOrRef = 0x41,
        TypeOrMethodDef = 0x4d,
        TypeRef = 1,
        TypeSpec = 0x1b,
        ULong = 0x63,
        UShort = 0x61
    }
}

