namespace System.Security.Principal
{
    using System;
    using System.Runtime.InteropServices;

    [ComVisible(false)]
    public enum WellKnownSidType
    {
        AccountAdministratorSid = 0x26,
        AccountCertAdminsSid = 0x2e,
        AccountComputersSid = 0x2c,
        AccountControllersSid = 0x2d,
        AccountDomainAdminsSid = 0x29,
        AccountDomainGuestsSid = 0x2b,
        AccountDomainUsersSid = 0x2a,
        AccountEnterpriseAdminsSid = 0x30,
        AccountGuestSid = 0x27,
        AccountKrbtgtSid = 40,
        AccountPolicyAdminsSid = 0x31,
        AccountRasAndIasServersSid = 50,
        AccountSchemaAdminsSid = 0x2f,
        AnonymousSid = 13,
        AuthenticatedUserSid = 0x11,
        BatchSid = 10,
        BuiltinAccountOperatorsSid = 30,
        BuiltinAdministratorsSid = 0x1a,
        BuiltinAuthorizationAccessSid = 0x3b,
        BuiltinBackupOperatorsSid = 0x21,
        BuiltinDomainSid = 0x19,
        BuiltinGuestsSid = 0x1c,
        BuiltinIncomingForestTrustBuildersSid = 0x38,
        BuiltinNetworkConfigurationOperatorsSid = 0x25,
        BuiltinPerformanceLoggingUsersSid = 0x3a,
        BuiltinPerformanceMonitoringUsersSid = 0x39,
        BuiltinPowerUsersSid = 0x1d,
        BuiltinPreWindows2000CompatibleAccessSid = 0x23,
        BuiltinPrintOperatorsSid = 0x20,
        BuiltinRemoteDesktopUsersSid = 0x24,
        BuiltinReplicatorSid = 0x22,
        BuiltinSystemOperatorsSid = 0x1f,
        BuiltinUsersSid = 0x1b,
        CreatorGroupServerSid = 6,
        CreatorGroupSid = 4,
        CreatorOwnerServerSid = 5,
        CreatorOwnerSid = 3,
        DialupSid = 8,
        DigestAuthenticationSid = 0x34,
        EnterpriseControllersSid = 15,
        InteractiveSid = 11,
        LocalServiceSid = 0x17,
        LocalSid = 2,
        LocalSystemSid = 0x16,
        LogonIdsSid = 0x15,
        MaxDefined = 60,
        NetworkServiceSid = 0x18,
        NetworkSid = 9,
        NTAuthoritySid = 7,
        NtlmAuthenticationSid = 0x33,
        NullSid = 0,
        OtherOrganizationSid = 0x37,
        ProxySid = 14,
        RemoteLogonIdSid = 20,
        RestrictedCodeSid = 0x12,
        SChannelAuthenticationSid = 0x35,
        SelfSid = 0x10,
        ServiceSid = 12,
        TerminalServerSid = 0x13,
        ThisOrganizationSid = 0x36,
        WinBuiltinTerminalServerLicenseServersSid = 60,
        WorldSid = 1
    }
}

