namespace System.Transactions.Oletx
{
    using System;

    internal enum OletxTransactionStatus
    {
        OLETX_TRANSACTION_STATUS_ABORTED = 0x200,
        OLETX_TRANSACTION_STATUS_ABORTING = 0x100,
        OLETX_TRANSACTION_STATUS_ALL = 0x7ffff,
        OLETX_TRANSACTION_STATUS_CLOSED = 0x40000,
        OLETX_TRANSACTION_STATUS_COMMITRETAINING = 0x80,
        OLETX_TRANSACTION_STATUS_COMMITTED = 0x400,
        OLETX_TRANSACTION_STATUS_COMMITTING = 0x40,
        OLETX_TRANSACTION_STATUS_FORCED_ABORT = 0x8000,
        OLETX_TRANSACTION_STATUS_FORCED_COMMIT = 0x10000,
        OLETX_TRANSACTION_STATUS_HEURISTIC_ABORT = 0x800,
        OLETX_TRANSACTION_STATUS_HEURISTIC_COMMIT = 0x1000,
        OLETX_TRANSACTION_STATUS_HEURISTIC_DAMAGE = 0x2000,
        OLETX_TRANSACTION_STATUS_HEURISTIC_DANGER = 0x4000,
        OLETX_TRANSACTION_STATUS_INDOUBT = 0x20000,
        OLETX_TRANSACTION_STATUS_NONE = 0,
        OLETX_TRANSACTION_STATUS_NOTPREPARED = 0x7ffc3,
        OLETX_TRANSACTION_STATUS_OPEN = 3,
        OLETX_TRANSACTION_STATUS_OPENNORMAL = 1,
        OLETX_TRANSACTION_STATUS_OPENREFUSED = 2,
        OLETX_TRANSACTION_STATUS_PREPARED = 8,
        OLETX_TRANSACTION_STATUS_PREPARERETAINED = 0x20,
        OLETX_TRANSACTION_STATUS_PREPARERETAINING = 0x10,
        OLETX_TRANSACTION_STATUS_PREPARING = 4
    }
}

