// Assembly mscorlib, Version 4.0.0.0

[assembly: System.Reflection.AssemblyKeyFile(@"f:\dd\Tools\devdiv\ecmapublickey.snk")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("System.Numerics, PublicKey=00000000000000000400000000000000", AllInternalsVisible=false)]
[assembly: System.Diagnostics.Debuggable(System.Diagnostics.DebuggableAttribute.DebuggingModes.IgnoreSymbolStoreSequencePoints)]
[assembly: System.Reflection.AssemblyDelaySign(true)]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("System, PublicKey=00000000000000000400000000000000", AllInternalsVisible=false)]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("System.Core, PublicKey=00000000000000000400000000000000", AllInternalsVisible=false)]
[assembly: System.Security.AllowPartiallyTrustedCallers]
[assembly: System.Resources.NeutralResourcesLanguage("en-US")]
[assembly: System.Runtime.CompilerServices.RuntimeCompatibility(WrapNonExceptionThrows=true)]
[assembly: System.Runtime.InteropServices.Guid("BED7F4EA-1A96-11d2-8F08-00A0C9A6186D")]
[assembly: System.Runtime.InteropServices.ComCompatibleVersion(1, 0, 0xce4, 0)]
[assembly: System.Runtime.InteropServices.TypeLibVersion(2, 4)]
[assembly: System.Runtime.CompilerServices.DefaultDependency(System.Runtime.CompilerServices.LoadHint.Always)]
[assembly: System.Runtime.CompilerServices.StringFreezing]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.CLSCompliant(true)]
[assembly: System.Runtime.CompilerServices.CompilationRelaxations(8)]
[assembly: System.Security.SecurityRules(System.Security.SecurityRuleSet.Level2, SkipVerificationInFullTrust=true)]
[assembly: System.Reflection.AssemblyTitle("mscorlib.dll")]
[assembly: System.Reflection.AssemblyDescription("mscorlib.dll")]
[assembly: System.Reflection.AssemblyDefaultAlias("mscorlib.dll")]
[assembly: System.Reflection.AssemblyCompany("Microsoft Corporation")]
[assembly: System.Reflection.AssemblyProduct("Microsoft\x00ae .NET Framework")]
[assembly: System.Reflection.AssemblyCopyright("\x00a9 Microsoft Corporation.  All rights reserved.")]
[assembly: System.Reflection.AssemblyFileVersion("4.0.30319.296")]
[assembly: System.Reflection.AssemblyInformationalVersion("4.0.30319.296")]
[assembly: System.Resources.SatelliteContractVersion("4.0.0.0")]
[assembly: System.Security.Permissions.SecurityPermission(System.Security.Permissions.SecurityAction.RequestMinimum, SkipVerification=true)]

