namespace System.Drawing.Drawing2D
{
    using System;

    public enum HatchStyle
    {
        BackwardDiagonal = 3,
        Cross = 4,
        DarkDownwardDiagonal = 20,
        DarkHorizontal = 0x1d,
        DarkUpwardDiagonal = 0x15,
        DarkVertical = 0x1c,
        DashedDownwardDiagonal = 30,
        DashedHorizontal = 0x20,
        DashedUpwardDiagonal = 0x1f,
        DashedVertical = 0x21,
        DiagonalBrick = 0x26,
        DiagonalCross = 5,
        Divot = 0x2a,
        DottedDiamond = 0x2c,
        DottedGrid = 0x2b,
        ForwardDiagonal = 2,
        Horizontal = 0,
        HorizontalBrick = 0x27,
        LargeCheckerBoard = 50,
        LargeConfetti = 0x23,
        LargeGrid = 4,
        LightDownwardDiagonal = 0x12,
        LightHorizontal = 0x19,
        LightUpwardDiagonal = 0x13,
        LightVertical = 0x18,
        Max = 4,
        Min = 0,
        NarrowHorizontal = 0x1b,
        NarrowVertical = 0x1a,
        OutlinedDiamond = 0x33,
        Percent05 = 6,
        Percent10 = 7,
        Percent20 = 8,
        Percent25 = 9,
        Percent30 = 10,
        Percent40 = 11,
        Percent50 = 12,
        Percent60 = 13,
        Percent70 = 14,
        Percent75 = 15,
        Percent80 = 0x10,
        Percent90 = 0x11,
        Plaid = 0x29,
        Shingle = 0x2d,
        SmallCheckerBoard = 0x31,
        SmallConfetti = 0x22,
        SmallGrid = 0x30,
        SolidDiamond = 0x34,
        Sphere = 0x2f,
        Trellis = 0x2e,
        Vertical = 1,
        Wave = 0x25,
        Weave = 40,
        WideDownwardDiagonal = 0x16,
        WideUpwardDiagonal = 0x17,
        ZigZag = 0x24
    }
}

