namespace Microsoft.SqlServer.Server
{
    using System;

    public enum TriggerAction
    {
        AlterAppRole = 0x8a,
        AlterAssembly = 0x66,
        AlterBinding = 0xaf,
        AlterFunction = 0x3e,
        AlterIndex = 0x19,
        AlterLogin = 0x91,
        AlterPartitionFunction = 0xc0,
        AlterPartitionScheme = 0xc3,
        AlterProcedure = 0x34,
        AlterQueue = 0x9e,
        AlterRole = 0x87,
        AlterRoute = 0xa5,
        AlterSchema = 0x8e,
        AlterService = 0xa2,
        AlterTable = 0x16,
        AlterTrigger = 0x48,
        AlterUser = 0x84,
        AlterView = 0x2a,
        CreateAppRole = 0x89,
        CreateAssembly = 0x65,
        CreateBinding = 0xae,
        CreateContract = 0x9a,
        CreateEventNotification = 0x4a,
        CreateFunction = 0x3d,
        CreateIndex = 0x18,
        CreateLogin = 0x90,
        CreateMsgType = 0x97,
        CreatePartitionFunction = 0xbf,
        CreatePartitionScheme = 0xc2,
        CreateProcedure = 0x33,
        CreateQueue = 0x9d,
        CreateRole = 0x86,
        CreateRoute = 0xa4,
        CreateSchema = 0x8d,
        CreateSecurityExpression = 0x1f,
        CreateService = 0xa1,
        CreateSynonym = 0x22,
        CreateTable = 0x15,
        CreateTrigger = 0x47,
        CreateType = 0x5b,
        CreateUser = 0x83,
        CreateView = 0x29,
        Delete = 3,
        DenyObject = 0xab,
        DenyStatement = 0xa8,
        DropAppRole = 0x8b,
        DropAssembly = 0x67,
        DropBinding = 0xb0,
        DropContract = 0x9c,
        DropEventNotification = 0x4c,
        DropFunction = 0x3f,
        DropIndex = 0x1a,
        DropLogin = 0x92,
        DropMsgType = 0x99,
        DropPartitionFunction = 0xc1,
        DropPartitionScheme = 0xc4,
        DropProcedure = 0x35,
        DropQueue = 0x9f,
        DropRole = 0x88,
        DropRoute = 0xa6,
        DropSchema = 0x8f,
        DropSecurityExpression = 0x21,
        DropService = 0xa3,
        DropSynonym = 0x24,
        DropTable = 0x17,
        DropTrigger = 0x49,
        DropType = 0x5d,
        DropUser = 0x85,
        DropView = 0x2b,
        GrantObject = 170,
        GrantStatement = 0xa7,
        Insert = 1,
        Invalid = 0,
        RevokeObject = 0xac,
        RevokeStatement = 0xa9,
        Update = 2
    }
}

