namespace System.Xml
{
    using System;

    internal enum BinXmlToken
    {
        Attr = 0xf6,
        CData = 0xf2,
        Comment = 0xf3,
        DocType = 0xfc,
        Element = 0xf8,
        Encoding = 0xfd,
        EndAttrs = 0xf5,
        EndCData = 0xf1,
        EndElem = 0xf7,
        EndNest = 0xeb,
        EOF = -1,
        Error = 0,
        Extn = 0xea,
        Name = 240,
        Nest = 0xec,
        NmFlush = 0xe9,
        NotImpl = -2,
        PI = 0xf4,
        Public = 250,
        QName = 0xef,
        SQL_BIGINT = 8,
        SQL_BINARY = 12,
        SQL_BIT = 6,
        SQL_CHAR = 13,
        SQL_DATETIME = 0x12,
        SQL_DECIMAL = 10,
        SQL_FLOAT = 4,
        SQL_IMAGE = 0x17,
        SQL_INT = 2,
        SQL_MONEY = 5,
        SQL_NCHAR = 14,
        SQL_NTEXT = 0x18,
        SQL_NUMERIC = 11,
        SQL_NVARCHAR = 0x11,
        SQL_REAL = 3,
        SQL_SMALLDATETIME = 0x13,
        SQL_SMALLINT = 1,
        SQL_SMALLMONEY = 20,
        SQL_TEXT = 0x16,
        SQL_TINYINT = 7,
        SQL_UDT = 0x1b,
        SQL_UUID = 9,
        SQL_VARBINARY = 15,
        SQL_VARCHAR = 0x10,
        Subset = 0xf9,
        System = 0xfb,
        XmlDecl = 0xfe,
        XmlText = 0xed,
        XSD_BASE64 = 0x85,
        XSD_BINHEX = 0x84,
        XSD_BOOLEAN = 0x86,
        XSD_BYTE = 0x88,
        XSD_DATE = 0x83,
        XSD_DATETIME = 130,
        XSD_DECIMAL = 0x87,
        XSD_KATMAI_DATE = 0x7f,
        XSD_KATMAI_DATEOFFSET = 0x7c,
        XSD_KATMAI_DATETIME = 0x7e,
        XSD_KATMAI_DATETIMEOFFSET = 0x7b,
        XSD_KATMAI_TIME = 0x7d,
        XSD_KATMAI_TIMEOFFSET = 0x7a,
        XSD_QNAME = 140,
        XSD_TIME = 0x81,
        XSD_UNSIGNEDINT = 0x8a,
        XSD_UNSIGNEDLONG = 0x8b,
        XSD_UNSIGNEDSHORT = 0x89
    }
}

