// Assembly System.Activities.DurableInstancing, Version 4.0.0.0

[assembly: System.Reflection.AssemblyKeyFile(@"f:\dd\tools\devdiv\35MSSharedLib1024.snk")]
[assembly: System.Runtime.InteropServices.Guid("3C5386D5-54BD-49dc-AFCC-A46EAE3545DB")]
[assembly: System.Resources.NeutralResourcesLanguage("en-US")]
[assembly: System.Runtime.CompilerServices.RuntimeCompatibility(WrapNonExceptionThrows=true)]
[assembly: System.Diagnostics.Debuggable(System.Diagnostics.DebuggableAttribute.DebuggingModes.IgnoreSymbolStoreSequencePoints)]
[assembly: System.Runtime.CompilerServices.CompilationRelaxations(8)]
[assembly: System.Runtime.CompilerServices.Extension]
[assembly: System.Reflection.AssemblyDefaultAlias("System.Activities.DurableInstancing.dll")]
[assembly: System.Resources.SatelliteContractVersion("4.0.0.0")]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.CLSCompliant(true)]
[assembly: System.Reflection.AssemblyTitle("System.Activities.DurableInstancing.dll")]
[assembly: System.Reflection.AssemblyDescription("System.Activities.DurableInstancing.dll")]
[assembly: System.Reflection.AssemblyDelaySign(true)]
[assembly: System.Reflection.AssemblyCompany("Microsoft Corporation")]
[assembly: System.Reflection.AssemblyProduct("Microsoft\x00ae .NET Framework")]
[assembly: System.Reflection.AssemblyCopyright("\x00a9 Microsoft Corporation.  All rights reserved.")]
[assembly: System.Reflection.AssemblyFileVersion("4.0.30319.245")]
[assembly: System.Reflection.AssemblyInformationalVersion("4.0.30319.245")]
[assembly: System.Security.Permissions.SecurityPermission(System.Security.Permissions.SecurityAction.RequestMinimum, Execution=true)]
[assembly: System.Security.Permissions.SecurityPermission(System.Security.Permissions.SecurityAction.RequestMinimum, SkipVerification=true)]

