namespace System.Management
{
    using System;

    internal enum tag_WBEM_PROVIDER_REQUIREMENTS_TYPE
    {
        WBEM_REQUIREMENTS_START_POSTFILTER,
        WBEM_REQUIREMENTS_STOP_POSTFILTER,
        WBEM_REQUIREMENTS_RECHECK_SUBSCRIPTIONS
    }
}

