namespace System.Management
{
    using System;

    internal enum tag_WMIQ_LANGUAGE_FEATURES
    {
        WMIQ_LF_LAST = 40,
        WMIQ_LF1_BASIC_SELECT = 1,
        WMIQ_LF10_COMPEX_SUBEXPRESSIONS = 10,
        WMIQ_LF11_ALIASING = 11,
        WMIQ_LF12_GROUP_BY_HAVING = 12,
        WMIQ_LF13_WMI_WITHIN = 13,
        WMIQ_LF14_SQL_WRITE_OPERATIONS = 14,
        WMIQ_LF15_GO = 15,
        WMIQ_LF16_SINGLE_LEVEL_TRANSACTIONS = 0x10,
        WMIQ_LF17_QUALIFIED_NAMES = 0x11,
        WMIQ_LF18_ASSOCIATONS = 0x12,
        WMIQ_LF19_SYSTEM_PROPERTIES = 0x13,
        WMIQ_LF2_CLASS_NAME_IN_QUERY = 2,
        WMIQ_LF20_EXTENDED_SYSTEM_PROPERTIES = 20,
        WMIQ_LF21_SQL89_JOINS = 0x15,
        WMIQ_LF22_SQL92_JOINS = 0x16,
        WMIQ_LF23_SUBSELECTS = 0x17,
        WMIQ_LF24_UMI_EXTENSIONS = 0x18,
        WMIQ_LF25_DATEPART = 0x19,
        WMIQ_LF26_LIKE = 0x1a,
        WMIQ_LF27_CIM_TEMPORAL_CONSTRUCTS = 0x1b,
        WMIQ_LF28_STANDARD_AGGREGATES = 0x1c,
        WMIQ_LF29_MULTI_LEVEL_ORDER_BY = 0x1d,
        WMIQ_LF3_STRING_CASE_FUNCTIONS = 3,
        WMIQ_LF30_WMI_PRAGMAS = 30,
        WMIQ_LF31_QUALIFIER_TESTS = 0x1f,
        WMIQ_LF32_SP_EXECUTE = 0x20,
        WMIQ_LF33_ARRAY_ACCESS = 0x21,
        WMIQ_LF34_UNION = 0x22,
        WMIQ_LF35_COMPLEX_SELECT_TARGET = 0x23,
        WMIQ_LF36_REFERENCE_TESTS = 0x24,
        WMIQ_LF37_SELECT_INTO = 0x25,
        WMIQ_LF38_BASIC_DATETIME_TESTS = 0x26,
        WMIQ_LF39_COUNT_COLUMN = 0x27,
        WMIQ_LF4_PROP_TO_PROP_TESTS = 4,
        WMIQ_LF40_BETWEEN = 40,
        WMIQ_LF5_COUNT_STAR = 5,
        WMIQ_LF6_ORDER_BY = 6,
        WMIQ_LF7_DISTINCT = 7,
        WMIQ_LF8_ISA = 8,
        WMIQ_LF9_THIS = 9
    }
}

