namespace System.Management
{
    using System;

    internal enum tag_WBEM_FLAVOR_TYPE
    {
        WBEM_FLAVOR_AMENDED = 0x80,
        WBEM_FLAVOR_DONT_PROPAGATE = 0,
        WBEM_FLAVOR_FLAG_PROPAGATE_TO_DERIVED_CLASS = 2,
        WBEM_FLAVOR_FLAG_PROPAGATE_TO_INSTANCE = 1,
        WBEM_FLAVOR_MASK_AMENDED = 0x80,
        WBEM_FLAVOR_MASK_ORIGIN = 0x60,
        WBEM_FLAVOR_MASK_PERMISSIONS = 0x10,
        WBEM_FLAVOR_MASK_PROPAGATION = 15,
        WBEM_FLAVOR_NOT_AMENDED = 0,
        WBEM_FLAVOR_NOT_OVERRIDABLE = 0x10,
        WBEM_FLAVOR_ORIGIN_LOCAL = 0,
        WBEM_FLAVOR_ORIGIN_PROPAGATED = 0x20,
        WBEM_FLAVOR_ORIGIN_SYSTEM = 0x40,
        WBEM_FLAVOR_OVERRIDABLE = 0
    }
}

