namespace System.Management
{
    using System;

    internal enum tag_WBEM_PATH_STATUS_FLAG
    {
        WBEMPATH_INFO_ANON_LOCAL_MACHINE = 1,
        WBEMPATH_INFO_CIM_COMPLIANT = 0x800,
        WBEMPATH_INFO_CONTAINS_SINGLETON = 0x100,
        WBEMPATH_INFO_HAS_IMPLIED_KEY = 0x80,
        WBEMPATH_INFO_HAS_MACHINE_NAME = 2,
        WBEMPATH_INFO_HAS_SUBSCOPES = 0x10,
        WBEMPATH_INFO_HAS_V2_REF_PATHS = 0x40,
        WBEMPATH_INFO_IS_CLASS_REF = 4,
        WBEMPATH_INFO_IS_COMPOUND = 0x20,
        WBEMPATH_INFO_IS_INST_REF = 8,
        WBEMPATH_INFO_IS_PARENT = 0x2000,
        WBEMPATH_INFO_IS_SINGLETON = 0x1000,
        WBEMPATH_INFO_NATIVE_PATH = 0x8000,
        WBEMPATH_INFO_PATH_HAD_SERVER = 0x20000,
        WBEMPATH_INFO_SERVER_NAMESPACE_ONLY = 0x4000,
        WBEMPATH_INFO_V1_COMPLIANT = 0x200,
        WBEMPATH_INFO_V2_COMPLIANT = 0x400,
        WBEMPATH_INFO_WMI_PATH = 0x10000
    }
}

