// Assembly Microsoft.JScript, Version 10.0.0.0

[assembly: System.Security.SecurityRules(System.Security.SecurityRuleSet.Level1, SkipVerificationInFullTrust=true)]
[assembly: System.Runtime.InteropServices.Guid("D3295D87-D604-11D4-A704-00C04FA137E4")]
[assembly: System.Security.AllowPartiallyTrustedCallers]
[assembly: System.Runtime.InteropServices.TypeLibVersion(10, 0)]
[assembly: System.Diagnostics.Debuggable(System.Diagnostics.DebuggableAttribute.DebuggingModes.IgnoreSymbolStoreSequencePoints)]
[assembly: System.Runtime.CompilerServices.CompilationRelaxations(8)]
[assembly: System.Runtime.Versioning.TargetFramework(".NETFramework,Version=v4.0", FrameworkDisplayName="")]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.CLSCompliant(false)]
[assembly: System.Reflection.AssemblyTitle("Microsoft.JScript.dll")]
[assembly: System.Reflection.AssemblyDescription("Microsoft.JScript.dll")]
[assembly: System.Reflection.AssemblyDefaultAlias("Microsoft.JScript.dll")]
[assembly: System.Reflection.AssemblyCompany("Microsoft Corporation")]
[assembly: System.Reflection.AssemblyProduct("Microsoft (R) Visual Studio (R) 2010")]
[assembly: System.Reflection.AssemblyCopyright("\x00a9 Microsoft Corporation. All rights reserved.")]
[assembly: System.Reflection.AssemblyFileVersion("10.0.30319.296")]
[assembly: System.Reflection.AssemblyInformationalVersion("10.0.30319.296")]
[assembly: System.Resources.SatelliteContractVersion("10.0.0.0")]
[assembly: System.Resources.NeutralResourcesLanguage("en-US")]
[assembly: System.Reflection.AssemblyDelaySign(true)]
[assembly: System.Reflection.AssemblyKeyFile(@"f:\dd\tools\devdiv\FinalPublicKey.snk")]
[assembly: System.Runtime.CompilerServices.RuntimeCompatibility(WrapNonExceptionThrows=true)]
[assembly: System.Security.Permissions.PermissionSet(System.Security.Permissions.SecurityAction.RequestOptional, Name="FullTrust")]
[assembly: System.Security.Permissions.ReflectionPermission(System.Security.Permissions.SecurityAction.RequestOptional, Unrestricted=true)]
[assembly: System.Security.Permissions.SecurityPermission(System.Security.Permissions.SecurityAction.RequestOptional, Flags=System.Security.Permissions.SecurityPermissionFlag.SerializationFormatter | System.Security.Permissions.SecurityPermissionFlag.ControlEvidence | System.Security.Permissions.SecurityPermissionFlag.UnmanagedCode)]
[assembly: System.Security.Permissions.FileIOPermission(System.Security.Permissions.SecurityAction.RequestOptional, Unrestricted=true)]
[assembly: System.Security.Permissions.RegistryPermission(System.Security.Permissions.SecurityAction.RequestOptional, Read=@"HKEY_LOCAL_MACHINE\SOFTWARE\Classes\PROTOCOLS\Handler")]

