// Assembly Accessibility, Version 4.0.0.0

[assembly: System.Reflection.AssemblyDescription("Accessibility.dll")]
[assembly: System.Runtime.InteropServices.ComVisible(true)]
[assembly: System.CLSCompliant(true)]
[assembly: System.Security.AllowPartiallyTrustedCallers]
[assembly: System.Diagnostics.Debuggable(System.Diagnostics.DebuggableAttribute.DebuggingModes.DisableOptimizations | System.Diagnostics.DebuggableAttribute.DebuggingModes.Default)]
[assembly: System.Reflection.AssemblyCopyright("\x00a9 Microsoft Corporation.  All rights reserved.")]
[assembly: System.Runtime.InteropServices.ImportedFromTypeLib("Accessibility")]
[assembly: System.Reflection.AssemblyFileVersion("4.0.30319.1")]
[assembly: System.Reflection.AssemblyTitle("Accessibility.dll")]
[assembly: System.Runtime.CompilerServices.CompilationRelaxations(8)]
[assembly: System.Reflection.AssemblyProduct("Microsoft\x00ae .NET Framework")]
[assembly: System.Reflection.AssemblyCompany("Microsoft Corporation")]
[assembly: System.Reflection.AssemblyInformationalVersion("4.0.30319.1")]
[assembly: System.Resources.NeutralResourcesLanguage("en-US")]
[assembly: System.Runtime.InteropServices.TypeLibVersion(1, 1)]
[assembly: System.Reflection.AssemblyDefaultAlias("Accessibility.dll")]
[assembly: System.Security.SecurityRules(System.Security.SecurityRuleSet.Level2, SkipVerificationInFullTrust=true)]
[assembly: System.Reflection.AssemblyKeyFile(@"f:\dd\tools\devdiv\FinalPublicKey.snk")]
[assembly: System.Runtime.InteropServices.Guid("1EA4DBF0-3C3B-11CF-810C-00AA00389B71")]
[assembly: System.Resources.SatelliteContractVersion("4.0.0.0")]
[assembly: System.Runtime.CompilerServices.RuntimeCompatibility(WrapNonExceptionThrows=true)]
[assembly: System.Reflection.AssemblyDelaySign(true)]
[assembly: System.Runtime.AssemblyTargetedPatchBand("1.0.21-0")]

