namespace System.Web.Management
{
    using System;

    internal enum WebEventType
    {
        WEBEVENT_BASE_EVENT,
        WEBEVENT_MANAGEMENT_EVENT,
        WEBEVENT_APP_LIFETIME_EVENT,
        WEBEVENT_REQUEST_EVENT,
        WEBEVENT_HEARTBEAT_EVENT,
        WEBEVENT_BASE_ERROR_EVENT,
        WEBEVENT_REQUEST_ERROR_EVENT,
        WEBEVENT_ERROR_EVENT,
        WEBEVENT_AUDIT_EVENT,
        WEBEVENT_SUCCESS_AUDIT_EVENT,
        WEBEVENT_AUTHENTICATION_SUCCESS_AUDIT_EVENT,
        WEBEVENT_FAILURE_AUDIT_EVENT,
        WEBEVENT_AUTHENTICATION_FAILURE_AUDIT_EVENT,
        WEBEVENT_VIEWSTATE_FAILURE_AUDIT_EVENT
    }
}

